### ISSUE TITLE
[5.3] Error Exception handling failed jobs

### ISSUE THREAD

**Issue by vrubiella** [vladimir-yuldashev/laravel-queue-rabbitmq#104]
Hello I having problems with jobs. 
This error not always occurs, but when is raised, all next jobs fails and raised this exception.

PHP 7.1
Laravel 5.3
vladimir-yuldashev/laravel-queue-rabbitmq 5.3 

```php
[2017-02-10 12:10:26] pre.ERROR: ErrorException: explode() expects parameter 2 to be string, array given in /www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:165
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'explode() expec...', '/www/vendor/lar...', 165, Array)
#1 /www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(165): explode('@', Array)
#2 /www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(69): Illuminate\Queue\Jobs\Job->parseJob(Array)
#3 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#4 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(Illuminate\Queue\WorkerOptions))
#5 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('rabbitmq', 'backend_api_job...', Object(Illuminate\Queue\WorkerOptions))
#6 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('rabbitmq', 'backend_api_job...', Object(Illuminate\Queue\WorkerOptions))
#7 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'backend_api_job...')
#8 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#9 /www/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#10 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#11 /www/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /www/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /www/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /www/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /www/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
```

And:

```php
Next ErrorException: Array to string conversion in /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:146
Stack trace:
#0 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(146): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/www/vendor/lar...', 146, Array)
#1 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\Queue\Console\WorkCommand->writeOutput(Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), true)
#2 [internal function]: Illuminate\Queue\Console\WorkCommand->Illuminate\Queue\Console\{closure}(Object(Illuminate\Queue\Events\JobFailed))
#3 /www/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#4 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(371): Illuminate\Events\Dispatcher->fire('Illuminate\\Queu...')
#5 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->raiseFailedJobEvent('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(ErrorException))
#6 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(289): Illuminate\Queue\Worker->failJob('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(ErrorException))
#7 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(233): Illuminate\Queue\Worker->markJobAsFailedIfHasExceededMaxAttempts('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), 5, Object(ErrorException))
#8 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(207): Illuminate\Queue\Worker->handleJobException('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(Illuminate\Queue\WorkerOptions), Object(ErrorException))
#9 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(152): Illuminate\Queue\Worker->process('rabbitmq', Object(VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob), Object(Illuminate\Queue\WorkerOptions))
#10 /www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('rabbitmq', 'backend_api_job...', Object(Illuminate\Queue\WorkerOptions))
#11 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('rabbitmq', 'backend_api_job...', Object(Illuminate\Queue\WorkerOptions))
#12 /www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'backend_api_job...')
#13 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#14 /www/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#15 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#16 /www/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /www/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /www/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /www/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /www/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /www/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main} 
```

**Comment by vladimir-yuldashev** [comment]
Hi.

You need to find job payload which causes this error.

**Comment by vrubiella** [comment]
Hello,

I flushed failed jobs and now I'm trying to reproduce the error another time but i can't :(.

Previuosly, analizing data on failed_job table, payload seems to be ok.

Important: Failed jobs were queued notifications.

I close the issue now, i will reopen it if I can reproduce the error another time.

Thanks!
